name: "blog_demo"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2025-03-24"
machine_id: 1

auth:
  jwt_expire: 8760   #jwt有效期24*365小时

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30   #最大时间
  max_backups: 7    #最大备份数量

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "blog_demo"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
